// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAttendance = "attendance"

// Attendance mapped from table <attendance>
type Attendance struct {
	ID             string  `gorm:"column:id;primaryKey" json:"id"`
	AttendanceTime *string `gorm:"column:attendance_time" json:"attendance_time"`
	UserID         *string `gorm:"column:user_id" json:"user_id"`
}

// TableName Attendance's table name
func (*Attendance) TableName() string {
	return TableNameAttendance
}

func (*Attendance) PrimaryKey() []string {
	return []string{"id"}
}