// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAuthGroupPermissions = "auth_group_permissions"

// AuthGroupPermissions mapped from table <auth_group_permissions>
type AuthGroupPermissions struct {
	ID           int32 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	GroupID      int32 `gorm:"column:group_id;not null" json:"group_id"`
	PermissionID int32 `gorm:"column:permission_id;not null" json:"permission_id"`
}

// TableName AuthGroupPermissions's table name
func (*AuthGroupPermissions) TableName() string {
	return TableNameAuthGroupPermissions
}

func (*AuthGroupPermissions) PrimaryKey() []string {
	return []string{"id"}
}