// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAuthUserGroups = "auth_user_groups"

// AuthUserGroups mapped from table <auth_user_groups>
type AuthUserGroups struct {
	ID      int32 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID  int32 `gorm:"column:user_id;not null" json:"user_id"`
	GroupID int32 `gorm:"column:group_id;not null" json:"group_id"`
}

// TableName AuthUserGroups's table name
func (*AuthUserGroups) TableName() string {
	return TableNameAuthUserGroups
}

func (*AuthUserGroups) PrimaryKey() []string {
	return []string{"id"}
}