// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCollectEvent = "collect_event"

// CollectEvent mapped from table <collect_event>
type CollectEvent struct {
	EventID      string     `gorm:"column:event_id;primaryKey" json:"event_id"`
	Group_       *string    `gorm:"column:group" json:"group"`
	Tag          *string    `gorm:"column:tag" json:"tag"`
	FromService  *string    `gorm:"column:from_service" json:"from_service"`
	ToService    *string    `gorm:"column:to_service" json:"to_service"`
	Params       *string    `gorm:"column:params" json:"params"`
	Success      *string    `gorm:"column:success" json:"success"`
	Result       *string    `gorm:"column:result" json:"result"`
	Msg          *string    `gorm:"column:msg" json:"msg"`
	CreateUserID *string    `gorm:"column:create_user_id" json:"create_user_id"`
	CreateTime   *time.Time `gorm:"column:create_time" json:"create_time"`
	ExcuteTime   *time.Time `gorm:"column:excute_time" json:"excute_time"`
	FinishTime   *time.Time `gorm:"column:finish_time" json:"finish_time"`
}

// TableName CollectEvent's table name
func (*CollectEvent) TableName() string {
	return TableNameCollectEvent
}

func (*CollectEvent) PrimaryKey() []string {
	return []string{"event_id"}
}