// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameConfigDetailChangeHistory = "config_detail_change_history"

// ConfigDetailChangeHistory mapped from table <config_detail_change_history>
type ConfigDetailChangeHistory struct {
	ChangeID       string  `gorm:"column:change_id;primaryKey" json:"change_id"`
	Before         *string `gorm:"column:before" json:"before"`
	After          *string `gorm:"column:after" json:"after"`
	Field          *string `gorm:"column:field" json:"field"`
	Value          *string `gorm:"column:value" json:"value"`
	Name           *string `gorm:"column:name" json:"name"`
	NameCopy       *string `gorm:"column:name_copy" json:"name_copy"`
	ConfigDetailID *string `gorm:"column:config_detail_id" json:"config_detail_id"`
	CreateUser     *string `gorm:"column:create_user" json:"create_user"`
	CreateTime     *string `gorm:"column:create_time" json:"create_time"`
	Operation      *string `gorm:"column:operation" json:"operation"`
	GroupID        *string `gorm:"column:group_id" json:"group_id"`
}

// TableName ConfigDetailChangeHistory's table name
func (*ConfigDetailChangeHistory) TableName() string {
	return TableNameConfigDetailChangeHistory
}

func (*ConfigDetailChangeHistory) PrimaryKey() []string {
	return []string{"change_id"}
}