// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameProject = "project"

// Project mapped from table <project>
type Project struct {
	ProjectID  string  `gorm:"column:project_id;primaryKey" json:"project_id"`
	Code       *string `gorm:"column:code" json:"code"`
	Name       *string `gorm:"column:name" json:"name"`
	CreateTime *string `gorm:"column:create_time" json:"create_time"`
	CreateUser *string `gorm:"column:create_user" json:"create_user"`
	IsDelete   *string `gorm:"column:is_delete" json:"is_delete"`
}

// TableName Project's table name
func (*Project) TableName() string {
	return TableNameProject
}

func (*Project) PrimaryKey() []string {
	return []string{"project_id"}
}