// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameReportGituserFix = "report_gituser_fix"

// ReportGituserFix mapped from table <report_gituser_fix>
type ReportGituserFix struct {
	PID         string  `gorm:"column:p_id;primaryKey" json:"p_id"` // ID
	CmsUserName *string `gorm:"column:cms_user_name" json:"cms_user_name"`
	GitUserName *string `gorm:"column:git_user_name" json:"git_user_name"`
}

// TableName ReportGituserFix's table name
func (*ReportGituserFix) TableName() string {
	return TableNameReportGituserFix
}

func (*ReportGituserFix) PrimaryKey() []string {
	return []string{"p_id"}
}