// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameReportGitcommitinfo = "report_gitcommitinfo"

// ReportGitcommitinfo mapped from table <report_gitcommitinfo>
type ReportGitcommitinfo struct {
	PID               string     `gorm:"column:p_id;primaryKey" json:"p_id"` // ID
	Ref               *string    `gorm:"column:ref" json:"ref"`
	ProjectID         *string    `gorm:"column:project_id" json:"project_id"` // 项目编码
	ProjectName       *string    `gorm:"column:project_name" json:"project_name"`
	CommitID          *string    `gorm:"column:commit_id" json:"commit_id"`
	CommitMessage     *string    `gorm:"column:commit_message" json:"commit_message"`
	CommitTime        *time.Time `gorm:"column:commit_time" json:"commit_time"`
	CommitAdditions   *int32     `gorm:"column:commit_additions" json:"commit_additions"`
	CommitDeletions   *int32     `gorm:"column:commit_deletions" json:"commit_deletions"`
	CommitTotal       *int32     `gorm:"column:commit_total" json:"commit_total"`
	CommitAuthorName  *string    `gorm:"column:commit_author_name" json:"commit_author_name"`
	CommitAuthorEmail *string    `gorm:"column:commit_author_email" json:"commit_author_email"`
	BatchID           *string    `gorm:"column:batch_id" json:"batch_id"`
	PathWithNamespace *string    `gorm:"column:path_with_namespace" json:"path_with_namespace"`
	CommitName        *string    `gorm:"column:commit_name" json:"commit_name"`
	CmsUserID         *string    `gorm:"column:cms_user_id" json:"cms_user_id"`
	CmsUserName       *string    `gorm:"column:cms_user_name" json:"cms_user_name"`
	CmsUserNick       *string    `gorm:"column:cms_user_nick" json:"cms_user_nick"`
	IssueKey          *string    `gorm:"column:issue_key" json:"issue_key"`
	GroupID           *string    `gorm:"column:group_id" json:"group_id"`
	ArtifactID        *string    `gorm:"column:artifact_id" json:"artifact_id"`
}

// TableName ReportGitcommitinfo's table name
func (*ReportGitcommitinfo) TableName() string {
	return TableNameReportGitcommitinfo
}

func (*ReportGitcommitinfo) PrimaryKey() []string {
	return []string{"p_id"}
}