// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRoleMenu = "role_menu"

// RoleMenu mapped from table <role_menu>
type RoleMenu struct {
	RoleMenuID string  `gorm:"column:role_menu_id;primaryKey" json:"role_menu_id"`
	RoleID     *string `gorm:"column:role_id" json:"role_id"`
	MenuID     *string `gorm:"column:menu_id" json:"menu_id"`
}

// TableName RoleMenu's table name
func (*RoleMenu) TableName() string {
	return TableNameRoleMenu
}

func (*RoleMenu) PrimaryKey() []string {
	return []string{"role_menu_id"}
}