// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSysMenu = "sys_menu"

// SysMenu mapped from table <sys_menu>
type SysMenu struct {
	MenuID     string  `gorm:"column:menu_id;primaryKey" json:"menu_id"`
	Name       *string `gorm:"column:name" json:"name"`
	MenuType   *string `gorm:"column:menu_type" json:"menu_type"`
	MenuURL    *string `gorm:"column:menu_url" json:"menu_url"`
	ParentID   *string `gorm:"column:parent_id" json:"parent_id"`
	OrderIndex *int32  `gorm:"column:order_index" json:"order_index"`
	Icon       *string `gorm:"column:icon" json:"icon"`
	Icon2      *string `gorm:"column:icon2" json:"icon2"`
}

// TableName SysMenu's table name
func (*SysMenu) TableName() string {
	return TableNameSysMenu
}

func (*SysMenu) PrimaryKey() []string {
	return []string{"menu_id"}
}