// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserAccount = "user_account"

// UserAccount mapped from table <user_account>
type UserAccount struct {
	UserID          string  `gorm:"column:user_id;primaryKey" json:"user_id"`
	Nick            *string `gorm:"column:nick" json:"nick"`
	UserName        *string `gorm:"column:user_name" json:"user_name"`
	Password        *string `gorm:"column:password" json:"password"`
	UserStatus      *string `gorm:"column:user_status" json:"user_status"`
	EntryDate       *string `gorm:"column:entry_date" json:"entry_date"`
	Email           *string `gorm:"column:email" json:"email"`
	Phone           *string `gorm:"column:phone" json:"phone"`
	LeaveDate       *string `gorm:"column:leave_date" json:"leave_date"`
	IsDelete        *string `gorm:"column:is_delete" json:"is_delete"`
	CreateTime      *string `gorm:"column:create_time" json:"create_time"`
	CreateUser      *string `gorm:"column:create_user" json:"create_user"`
	ModifyUser      *string `gorm:"column:modify_user" json:"modify_user"`
	ModifyTime      *string `gorm:"column:modify_time" json:"modify_time"`
	WorkCode        *string `gorm:"column:work_code" json:"work_code"`
	CreateLdap      *string `gorm:"column:create_ldap" json:"create_ldap"`
	LadpUserLoginID *string `gorm:"column:ladp_user_login_id" json:"ladp_user_login_id"`
	LeaveReason     *string `gorm:"column:leave_reason" json:"leave_reason"`
	WechatID        *string `gorm:"column:wechat_id" json:"wechat_id"`
	AttendanceID    *string `gorm:"column:attendance_id" json:"attendance_id"`
}

// TableName UserAccount's table name
func (*UserAccount) TableName() string {
	return TableNameUserAccount
}

func (*UserAccount) PrimaryKey() []string {
	return []string{"user_id"}
}