// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserChangeHistory = "user_change_history"

// UserChangeHistory mapped from table <user_change_history>
type UserChangeHistory struct {
	ChangeID   string  `gorm:"column:change_id;primaryKey" json:"change_id"`
	Before     *string `gorm:"column:before" json:"before"`
	After      *string `gorm:"column:after" json:"after"`
	Field      *string `gorm:"column:field" json:"field"`
	Value      *string `gorm:"column:value" json:"value"`
	Name       *string `gorm:"column:name" json:"name"`
	UserID     *string `gorm:"column:user_id" json:"user_id"`
	CreateUser *string `gorm:"column:create_user" json:"create_user"`
	CreateTime *string `gorm:"column:create_time" json:"create_time"`
	Operation  *string `gorm:"column:operation" json:"operation"`
}

// TableName UserChangeHistory's table name
func (*UserChangeHistory) TableName() string {
	return TableNameUserChangeHistory
}

func (*UserChangeHistory) PrimaryKey() []string {
	return []string{"change_id"}
}