// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserRole = "user_role"

// UserRole mapped from table <user_role>
type UserRole struct {
	UserRoleID string  `gorm:"column:user_role_id;primaryKey" json:"user_role_id"`
	RoleID     *string `gorm:"column:role_id" json:"role_id"`
	UserID     *string `gorm:"column:user_id" json:"user_id"`
}

// TableName UserRole's table name
func (*UserRole) TableName() string {
	return TableNameUserRole
}

func (*UserRole) PrimaryKey() []string {
	return []string{"user_role_id"}
}